name: flash_dash_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # แนะนำให้ใช้ช่วงเวอร์ชันที่กว้างขึ้นเล็กน้อย

dependencies:
  flutter:
    sdk: flutter

  # Core & UI Packages
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.3.1
  material_symbols_icons: ^4.2764.0
  dotted_border: ^2.1.0
  image_picker: ^1.2.0

  # Map & Location Packages
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  osm_nominatim: ^4.0.1
  location: ^8.0.1
  flutter_launcher_icons: ^0.13.1
  
  # Networking
  http: ^1.2.1 # ++ ย้ายมาจาก dev_dependencies ++

  # Firebase Packages
  firebase_core: ^3.2.0   # ++ เพิ่มเข้ามา (สำคัญที่สุด) ++
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon" # ตั้งค่าสำหรับ Android
  image_path: "assets/image/logo_flash_dash.png" 
  min_sdk_android: 21



flutter:
  uses-material-design: true
  assets:
    - assets/image/

